LANGUAGE_MAP = {
    "python": {
        "function": ["function_definition"],
        "if": ["if_statement"],
        "else": ["else_clause", "elif_clause"],
        "loop": ["for_statement", "while_statement"],
        "try": ["try_statement"],
        "except": ["except_clause"],
        "finally": ["finally_clause"],
        "return": ["return_statement"],
    },
    "javascript": {
        "function": ["function_declaration"],
        "if": ["if_statement"],
        "else": ["else_clause"],
        "loop": ["for_statement", "while_statement", "do_statement"],
        "try": ["try_statement"],
        "except": ["catch_clause"],
        "finally": ["finally_clause"],
        "return": ["return_statement"],
    },
    "java": {
        "function": ["method_declaration"],
        "if": ["if_statement"],
        "else": ["else_statement"],
        "loop": ["for_statement", "while_statement", "enhanced_for_statement"],
        "try": ["try_statement"],
        "except": ["catch_clause"],
        "finally": ["finally_clause"],
        "return": ["return_statement"],
    },
    "cpp": {
        "function": ["function_definition"],
        "if": ["if_statement"],
        "else": ["else_statement"],
        "loop": ["for_statement", "while_statement"],
        "try": ["try_statement"],
        "except": ["catch_clause"],
        "finally": ["finally_clause"],
        "return": ["return_statement"],
    },
}
